### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by domschl** [winterscar/functional-avr#2]
This project is a very useful extension for small AVRs.

Please clarify the license of your project.

I would be interested in reusing it with the [muwerk project](https://github.com/muwerk), a scheduler with event-messaging, which uses the permissible [MIT license](https://choosealicense.com/licenses/mit/).

**Comment by winterscar** [comment]
Glad you find it useful :)

I've added the MIT Licence.

**Comment by domschl** [comment]
Thank you!
